# coding: utf-8

"""
    Selling Partner API for Orders

    Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_v0_api import OrdersV0Api  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersV0Api(unittest.TestCase):
    """OrdersV0Api unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.orders_v0_api.OrdersV0Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_confirm_shipment(self):
        """Test case for confirm_shipment

        """
        pass

    def test_get_order(self):
        """Test case for get_order

        """
        pass

    def test_get_order_address(self):
        """Test case for get_order_address

        """
        pass

    def test_get_order_buyer_info(self):
        """Test case for get_order_buyer_info

        """
        pass

    def test_get_order_items(self):
        """Test case for get_order_items

        """
        pass

    def test_get_order_items_buyer_info(self):
        """Test case for get_order_items_buyer_info

        """
        pass

    def test_get_order_regulated_info(self):
        """Test case for get_order_regulated_info

        """
        pass

    def test_get_orders(self):
        """Test case for get_orders

        """
        pass

    def test_update_verification_status(self):
        """Test case for update_verification_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
