"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os
import base64
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent   # this points to Profit-Tracker
load_dotenv(ROOT_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-pkux+0mhylu3^+n5l_t%bu*89wmoz46)vg63zs64tl=31p9oj1'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = os.getenv("DEBUG") == "True"

MYNTRA_MERCHANT_ID = os.getenv("MYNTRA_MERCHANT_ID")
MYNTRA_SECRET_KEY = os.getenv("MYNTRA_SECRET_KEY")
MYNTRA_WAREHOUSE_CODE = os.getenv("MYNTRA_WAREHOUSE_CODE")
MYNTRA_PARTNER_TYPE = os.getenv("MYNTRA_PARTNER_TYPE")
# MYNTRA_BASIC_AUTH = "OEJWREdGQ0s6b0VjNHN1WkhlSmtyZjBvdGdCZ2hOQTZ5REhDM29DR1ViQktFZ0Q="
MYNTRA_BASE_URL = "https://api-integration.myntra.com"
# print("MYNTRA ID:", MYNTRA_MERCHANT_ID)
MYNTRA_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZl9pZCI6IjcwMDAwMDEiLCJyZXRhaWxlcl9pZCI6IjY4ZDNiNDAxOTgwOWY5YjAyMzJhMzQyNCIsInBhcnRuZXJfaWQiOiI1NzkyMCIsIm1lcmNoYW50X2lkIjoiOEJWREdGQ0siLCJyZXRhaWxlcl9uYW1lIjoiTGliZXJldHRlIENyZWF0aW9ucyIsInNlbGxlcl9pZCI6IjU3OTIwIiwicEJhcmNvZGUiOiJNWU5UUkEtVHJhY2tNeVByb2ZpdC1MTlJOVEEiLCJvcmlnaW4iOiIiLCJpZ25vcmVFeHBpcmF0aW9uIjpmYWxzZSwiaWF0IjoxNzcyNzc2NDgzLCJleHAiOjE3NzUzNjg0ODN9.uDGkDeZ-9RNglySvO-Y34XKaoF8_Pb1Fe1pWUEUEyGw"
basic_auth = f"{MYNTRA_MERCHANT_ID}:{MYNTRA_SECRET_KEY}"
MYNTRA_BASIC_TOKEN = base64.b64encode(basic_auth.encode()).decode()



#Amazon
LWA_APP_ID = os.getenv("LWA_APP_ID")
LWA_CLIENT_SECRET = os.getenv("LWA_CLIENT_SECRET")
SP_API_REFRESH_TOKEN = os.getenv("SP_API_REFRESH_TOKEN")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_ROLE_ARN = os.getenv("AWS_ROLE_ARN")

ALLOWED_HOSTS = ['trackmyprofit.com', 'www.trackmyprofit.com', '194.238.17.204','api.trackmyprofit.com','127.0.0.1', "localhost" ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://192.168.1.9",
    "http://192.168.1.9:8000",
    "http://192.168.1.9:8000",
    "http://localhost:8000",
    "http://localhost:8001",
    "http://0.0.0.0:8000",
    "http://192.168.1.9",
    "https://trackmyprofit.com",
    "https://www.trackmyprofit.com",
    "https://api.trackmyprofit.com",
    "http://localhost:3000",
    "http://localhost:3001",
]
 
CORS_ALLOW_CREDENTIALS = True
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8), 
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'admin_auth',
    'user_auth',
    'drf_yasg',
    'subscription',
    'myntra', 
    'amazon',

]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET")
#SECRET_KEY = os.getenv("SECRET_KEY")
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key")


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'
#STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
