# Generated by Django 4.2.7 on 2026-08-17 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('SP-API', 'Amazon SP-API'), ('Amazon-Ads', 'Amazon Ads API'), ('Myntra', 'Myntra API')], default='SP-API', max_length=50)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('call_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('orders_processed', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
