# Generated by Django 5.1.4 on 2026-02-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=0)),
                ('shipping_fee', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('payout', models.FloatField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myntra.myntraorder')),
            ],
        ),
    ]
