# Generated by Django 5.1.4 on 2026-02-16 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myntraorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
