# Generated by Django 5.2.7 on 2026-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0002_alter_myntraorder_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myntraorder',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='status',
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='logistics_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
