# Generated by Django 5.2.7 on 2026-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0003_rename_order_date_myntraorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myntraorder',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
