# Generated by Django 5.2.7 on 2026-03-26 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0004_myntraorder_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='myntraorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myntra_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='MyntraConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myntra_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
