# Generated by Django 4.2.7 on 2026-07-04 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myntra', '0005_myntraorder_user_alter_myntraorder_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraReturnItemNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('order_line_id', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('return_type', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('return_warehouse_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('ready_for_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_id', models.CharField(blank=True, max_length=50, null=True)),
                ('myntra_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myntra.myntraconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraPaymentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_number', models.CharField(db_index=True, max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('year_month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr_details_link', models.TextField(blank=True, null=True)),
                ('advice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('myntra_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myntra.myntraconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraOrderNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('uidx', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_code', models.CharField(blank=True, max_length=100, null=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myntra_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myntra.myntraconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myntra_orders_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraOrderItemNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('line_final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pack_by_time', models.DateTimeField(blank=True, null=True)),
                ('accept_by_time', models.DateTimeField(blank=True, null=True)),
                ('customer_promise_time', models.DateTimeField(blank=True, null=True)),
                ('ship_by_time', models.DateTimeField(blank=True, null=True)),
                ('unit_other_charges_without_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myntra.myntraordernew')),
            ],
        ),
    ]
