# Generated by Django 4.2.7 on 2026-07-29 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0006_myntrareturnitemnew_myntrapaymentnew_myntraordernew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('style_status', models.CharField(blank=True, max_length=20, null=True)),
                ('style_status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('style_id', models.CharField(blank=True, max_length=50, null=True)),
                ('style_name', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_sku_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_id', models.CharField(max_length=50, unique=True)),
                ('sku_code', models.CharField(blank=True, max_length=255, null=True)),
                ('van', models.CharField(blank=True, max_length=255, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('listing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('listing_status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_listing_comments', models.TextField(blank=True, null=True)),
                ('style_catalogued_date', models.DateField(blank=True, null=True)),
                ('lot_uploaded_date', models.DateField(blank=True, null=True)),
                ('style_onhold_date', models.DateField(blank=True, null=True)),
                ('onhold_reason', models.TextField(blank=True, null=True)),
                ('turn_around_time', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['seller_sku_code'],
            },
        ),
        migrations.CreateModel(
            name='MyntraReportQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(choices=[('Seller_Orders_Report', 'Seller Orders Report'), ('Seller_Returns_Report', 'Seller Returns Report'), ('Seller_Inventory_Report', 'Seller Inventory Report'), ('Seller_Listings_Report', 'Seller Listing Report'), ('Seller_Payment_Report', 'Seller Payment Report'), ('Seller_WPR_Report', 'Seller WPR Report')], max_length=100)),
                ('partner_type', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('download_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse_id', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('myntra_sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('style_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('order_created_date', models.DateField(blank=True, null=True)),
                ('inscanned_on', models.DateField(blank=True, null=True)),
                ('fmpu_date', models.DateField(blank=True, null=True)),
                ('order_delivered_date', models.DateField(blank=True, null=True)),
                ('return_created_date', models.DateField(blank=True, null=True)),
                ('refunded_date', models.DateField(blank=True, null=True)),
                ('order_rto_date', models.DateField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('exchange_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_line_id', models.CharField(max_length=100, unique=True)),
                ('seller_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('store_packet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_packet_id_fk', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('return_id', models.CharField(blank=True, max_length=100, null=True)),
                ('return_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, max_length=100, null=True)),
                ('forward_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('master_bag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lmdo_status', models.CharField(blank=True, max_length=100, null=True)),
                ('lmdo_last_modified_on', models.DateField(blank=True, null=True)),
                ('gatepass_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gatepass_status', models.CharField(blank=True, max_length=100, null=True)),
                ('gatepass_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gatepass_lastmodified', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='myntraorder',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='logistics_fee',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='myntraorder',
            name='sku',
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='article_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='cancellation_reason_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='courier_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='fmpu_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='gift_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='inscanned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='lost_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='myntra_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_reports', to='myntra.myntraconnection'),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='myntra_sku_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='order_id_fk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='order_line_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='order_release_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='order_tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='packed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='packet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='po_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='return_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='rto_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_order_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_packet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_sku_code',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='seller_warehouse_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='shipped_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='sku_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='store_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='style_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='style_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='tax_recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='total_mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='vendor_article_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='warehouse_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myntraorder',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='myntraorder',
            index=models.Index(fields=['seller_order_id'], name='myntra_mynt_seller__ea1e27_idx'),
        ),
        migrations.AddIndex(
            model_name='myntraorder',
            index=models.Index(fields=['seller_sku_code'], name='myntra_mynt_seller__5a4864_idx'),
        ),
        migrations.AddIndex(
            model_name='myntraorder',
            index=models.Index(fields=['order_status'], name='myntra_mynt_order_s_8dab3e_idx'),
        ),
        migrations.AddIndex(
            model_name='myntraorder',
            index=models.Index(fields=['created_on'], name='myntra_mynt_created_15182d_idx'),
        ),
        migrations.AddField(
            model_name='myntrareturn',
            name='myntra_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='myntra.myntraconnection'),
        ),
        migrations.AddField(
            model_name='myntrareportqueue',
            name='myntra_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_queue', to='myntra.myntraconnection'),
        ),
        migrations.AddField(
            model_name='myntralisting',
            name='myntra_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='myntra.myntraconnection'),
        ),
        migrations.AlterUniqueTogether(
            name='myntrareportqueue',
            unique_together={('myntra_connection', 'report_name', 'from_date', 'to_date')},
        ),
    ]
