# Generated by Django 4.2.7 on 2026-07-29 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0007_myntralisting_myntrareportqueue_myntrareturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myntraorder',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='myntra_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reports', to='myntra.myntraconnection'),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='order_line_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='seller_order_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myntraorder',
            name='seller_sku_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
