# Generated by Django 4.2.7 on 2026-07-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0008_alter_myntraorder_imported_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neft_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('order_line_id', models.CharField(max_length=100)),
                ('seller_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('return_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('pick_and_pack_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fixed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_gateway_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('logistics_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('igst_tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst_tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sgst_tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seller_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('platform_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myntra_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='myntra.myntraconnection')),
            ],
            options={
                'ordering': ['-payment_date', 'order_line_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='myntrapaymenttransaction',
            constraint=models.UniqueConstraint(fields=('order_line_id', 'order_type', 'comments'), name='unique_myntra_payment_transaction'),
        ),
    ]
