# Generated by Django 4.2.7 on 2026-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0009_myntrapaymenttransaction_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myntrapaymenttransaction',
            name='unique_myntra_payment_transaction',
        ),
        migrations.AddConstraint(
            model_name='myntrapaymenttransaction',
            constraint=models.UniqueConstraint(fields=('neft_ref', 'order_line_id', 'order_type', 'comments'), name='unique_myntra_payment_transaction'),
        ),
    ]
