# Generated by Django 4.2.7 on 2026-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0010_remove_myntrapaymenttransaction_unique_myntra_payment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myntraconnection',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntraconnection',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
