# Generated by Django 4.2.7 on 2026-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0011_myntraconnection_access_token_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myntrapaymenttransaction',
            name='unique_myntra_payment_transaction',
        ),
        migrations.AddField(
            model_name='myntrapaymenttransaction',
            name='nod_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntrapaymenttransaction',
            name='transaction_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='myntrapaymenttransaction',
            name='order_line_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='myntrapaymenttransaction',
            constraint=models.UniqueConstraint(fields=('myntra_connection', 'transaction_key'), name='unique_myntra_payment_transaction_key'),
        ),
    ]
