# Generated by Django 4.2.7 on 2026-08-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0012_remove_myntrapaymenttransaction_unique_myntra_payment_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myntraordernew',
            name='myntra_connection',
        ),
        migrations.RemoveField(
            model_name='myntraordernew',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myntrapaymentnew',
            name='myntra_connection',
        ),
        migrations.RemoveField(
            model_name='myntrapaymentnew',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myntrareturnitemnew',
            name='myntra_connection',
        ),
        migrations.RemoveField(
            model_name='myntrareturnitemnew',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myntrasettlement',
            name='order',
        ),
        migrations.DeleteModel(
            name='MyntraOrderItemNew',
        ),
        migrations.DeleteModel(
            name='MyntraOrderNew',
        ),
        migrations.DeleteModel(
            name='MyntraPaymentNew',
        ),
        migrations.DeleteModel(
            name='MyntraReturnItemNew',
        ),
        migrations.DeleteModel(
            name='MyntraSettlement',
        ),
    ]
