# Generated by Django 4.2.7 on 2026-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0013_remove_myntraordernew_myntra_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myntralisting',
            name='gst_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myntralisting',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myntralisting',
            name='standard_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='myntralisting',
            name='tcs',
            field=models.FloatField(default=0),
        ),
    ]
