# Generated by Django 4.2.27 on 2026-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0014_myntralisting_gst_rate_myntralisting_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myntralisting',
            name='tds',
            field=models.FloatField(default=0),
        ),
    ]
