# Generated by Django 4.2.27 on 2026-09-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myntra', '0015_myntralisting_tds'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(default='Myntra', max_length=50)),
                ('report_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploaded_reports/')),
                ('status', models.CharField(default='Processed', max_length=50)),
                ('records', models.CharField(default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_report_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
