# Generated by Django 4.2.7 on 2026-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_legaldocument_promocode_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10),
        ),
    ]
