# Generated by Django 4.2.7 on 2026-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_subscriptionplan_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('about_us', 'About Us'), ('third_party_policy', 'Third Party Policy'), ('plateform_policy', 'Platform Policy'), ('return_policy', 'Return Policy'), ('contact_us', 'Contact Us')], max_length=50),
        ),
    ]
