# Generated by Django 4.2.7 on 2026-06-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_subscriptionplan_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='annualPlan',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='monthlyPlan',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('about_us', 'About Us'), ('third_party_policy', 'Third Party Policy'), ('plateform_policy', 'Platform Policy'), ('return_policy', 'Return Policy'), ('contact_us', 'Contact Us')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
