# Generated by Django 4.2.7 on 2026-06-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_legaldocument_title'),
        ('user_auth', '0008_notification_usernotification'),
    ]

    operations = [
    ]
