# Generated by Django 4.2.7 on 2026-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='support_tickets/'),
        ),
    ]
