# Generated by Django 4.2.7 on 2026-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_supportticket_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='user_auth.module'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='submodules',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='user_auth.submodule'),
        ),
    ]
