# Generated by Django 4.2.7 on 2026-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_legaldocument_title'),
        ('user_auth', '0012_subscriptionplan_modules_subscriptionplan_submodules'),
    ]

    operations = [
    ]
