# Generated by Django 4.2.7 on 2026-07-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_merge_20260625_1213'),
        ('user_auth', '0013_merge_20260706_0926'),
    ]

    operations = [
    ]
