# Generated by Django 4.2.7 on 2026-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_merge_20260707_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
    ]
