# Generated by Django 4.2.7 on 2026-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_merge_20260707_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='initial_sync_duration',
            field=models.PositiveIntegerField(default=30, help_text='Number of historical days included in this subscription plan.'),
        ),
    ]
