# Generated by Django 4.2.7 on 2026-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_alter_subuser_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='role',
            field=models.CharField(blank=True, default='Staff', max_length=50, null=True),
        ),
    ]
