# Generated by Django 4.2.7 on 2026-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_subscriptionplan_initial_sync_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=50),
        ),
    ]
