# Generated by Django 4.2.7 on 2026-08-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_alter_subuser_mobile_number_and_more'),
        ('user_auth', '0016_subuser_role'),
    ]

    operations = [
    ]
