# Generated by Django 4.2.27 on 2026-08-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_adminsubuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('client', 'Client Module'), ('admin', 'Admin Module')], default='client', max_length=20),
        ),
    ]
