# Generated by Django 4.2.7 on 2026-08-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0022_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_channel_connection',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of channel connections (Amazon, Myntra, Ads, etc.) allowed under this subscription plan.'),
        ),
    ]
