# Generated by Django 4.2.7 on 2026-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_subscriptionplan_max_channel_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive - No plan chosen'), ('active', 'Active'), ('trial', 'Free Trial Active'), ('paid', 'Paid Subscription Active')], default='inactive', max_length=50),
        ),
    ]
