# Generated by Django 5.2.7 on 2026-03-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_client_id', models.CharField(max_length=255)),
                ('app_client_secret', models.CharField(max_length=255)),
                ('seller_central_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_encrypted', models.TextField()),
                ('region', models.CharField(default='NA', max_length=10)),
                ('marketplace_id', models.CharField(default='ATVPDKIKX0DER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
