# Generated by Django 4.2.7 on 2026-04-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_order_id', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('last_update_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('fulfillment_channel', models.CharField(max_length=20)),
                ('items_shipped', models.IntegerField()),
                ('items_unshipped', models.IntegerField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
