# Generated by Django 4.2.7 on 2026-04-09 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0004_financialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_report_id', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(max_length=100)),
                ('processing_status', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField()),
                ('data_start_time', models.DateTimeField(blank=True, null=True)),
                ('data_end_time', models.DateTimeField(blank=True, null=True)),
                ('report_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
