# Generated by Django 4.2.7 on 2026-04-10 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='amazon_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_events', to='amazon_auth.amazonaccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='amazon_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='amazon_auth.amazonaccount'),
        ),
        migrations.AddField(
            model_name='report',
            name='amazon_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='amazon_auth.amazonaccount'),
        ),
        migrations.AlterField(
            model_name='amazonaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='amazon_order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='amazon_report_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('amazon_account', 'amazon_order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('amazon_account', 'amazon_report_id')},
        ),
    ]
