# Generated by Django 4.2.7 on 2026-04-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0006_financialevent_amazon_account_order_amazon_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=50)),
                ('seller_sku', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_shipped', models.IntegerField(blank=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amazon_auth.order')),
            ],
        ),
    ]
