# Generated by Django 4.2.7 on 2026-04-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='financialevent',
            unique_together={('amazon_account', 'unique_hash')},
        ),
    ]
