# Generated by Django 4.2.7 on 2026-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0008_financialevent_unique_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='asin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
