# Generated by Django 4.2.7 on 2026-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0010_orderitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_sku', models.CharField(max_length=100, unique=True)),
                ('parent_sku', models.CharField(max_length=100)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='financialevent',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='fulfillment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(db_index=True, default='Amazon-India', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parent_sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_replaced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='seller_sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['amazon_account'], name='amazon_auth_amazon__002321_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['posted_date'], name='amazon_auth_posted__85e6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['amazon_order_id'], name='amazon_auth_amazon__306543_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller_sku'], name='amazon_auth_seller__9c69ac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['asin'], name='amazon_auth_asin_a04e3c_idx'),
        ),
    ]
