# Generated by Django 4.2.7 on 2026-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0011_productmapping_financialevent_commission_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_orders', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='amazon_auth_sku_ad0916_idx'), models.Index(fields=['date'], name='amazon_auth_date_cc6589_idx')],
            },
        ),
    ]
