# Generated by Django 4.2.7 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0012_adreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingCatalogQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_sku', models.CharField(max_length=255, unique=True)),
                ('asin', models.CharField(max_length=50)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
