# Generated by Django 4.2.7 on 2026-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0013_missingcatalogqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingcatalogqueue',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
