# Generated by Django 4.2.7 on 2026-04-22 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0014_missingcatalogqueue_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccount',
            name='ads_cookie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonaccount',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(db_index=True, max_length=100)),
                ('campaign_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=50, null=True)),
                ('targeting_type', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_name', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='amazon_auth.amazonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('amazon_account', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='AdCampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roas', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('impressions_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='amazon_auth.adcampaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
