# Generated by Django 4.2.7 on 2026-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0015_amazonaccount_ads_cookie_amazonaccount_csrf_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccount',
            name='csrf_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
