# Generated by Django 4.2.7 on 2026-04-22 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0016_amazonaccount_csrf_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ordered_product_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordered_product_sales_b2b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('units_ordered', models.IntegerField(default=0)),
                ('units_ordered_b2b', models.IntegerField(default=0)),
                ('total_order_items', models.IntegerField(default=0)),
                ('sessions_total', models.IntegerField(default=0)),
                ('order_item_session_percentage', models.FloatField(default=0)),
                ('units_refunded', models.IntegerField(default=0)),
                ('refund_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_auth.amazonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('amazon_account', 'date')},
            },
        ),
    ]
