# Generated by Django 4.2.7 on 2026-04-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0017_businessreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('report_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('report_type', models.CharField(max_length=100)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('data_start_time', models.DateTimeField(blank=True, null=True)),
                ('data_end_time', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_QUEUE', 'In Queue'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('download_status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADED', 'Downloaded'), ('PARSED', 'Parsed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('processing_start_time', models.DateTimeField(blank=True, null=True)),
                ('processing_end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_reports', to='amazon_auth.amazonaccount')),
            ],
        ),
    ]
