# Generated by Django 4.2.7 on 2026-04-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0018_amazonreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_order_id', models.CharField(db_index=True, max_length=50)),
                ('data_start_time', models.DateTimeField()),
                ('data_end_time', models.DateTimeField()),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('report_id', models.CharField(blank=True, max_length=100, null=True)),
                ('report_document_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_summaries', to='amazon_auth.amazonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['amazon_order_id'], name='amazon_auth_amazon__a2e8f2_idx'), models.Index(fields=['data_start_time', 'data_end_time'], name='amazon_auth_data_st_f0ddb5_idx')],
                'unique_together': {('amazon_account', 'amazon_order_id', 'data_start_time', 'data_end_time')},
            },
        ),
    ]
