# Generated by Django 4.2.7 on 2026-04-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0019_settlementordersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='asin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
