# Generated by Django 4.2.7 on 2026-04-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0020_productmapping_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingcatalogqueue',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_queue', to='amazon_auth.amazonaccount'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_auth.amazonaccount'),
        ),
        migrations.AlterField(
            model_name='missingcatalogqueue',
            name='seller_sku',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='seller_sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='missingcatalogqueue',
            unique_together={('seller_sku', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together={('seller_sku', 'account')},
        ),
    ]
