# Generated by Django 4.2.7 on 2026-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0021_missingcatalogqueue_account_productmapping_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='event_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
