# Generated by Django 4.2.7 on 2026-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0023_financialevent_shipping_income_orderitem_claim_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='buy_box_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='buy_box_percentage_b2b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='child_asin',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='orders_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='page_views_browser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='page_views_mobile_app',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='page_views_percentage_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='page_views_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='page_views_total_b2b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='parent_asin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='session_percentage_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='sessions_browser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='sessions_mobile_app',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='sessions_total_b2b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='shipped_product_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='total_order_items_b2b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='unit_session_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='unit_session_percentage_b2b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessreport',
            name='units_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='businessreport',
            constraint=models.UniqueConstraint(fields=('amazon_account', 'date', 'parent_asin', 'child_asin'), name='unique_business_report'),
        ),
        migrations.RemoveField(
            model_name='businessreport',
            name='order_item_session_percentage',
        ),
    ]
