# Generated by Django 4.2.7 on 2026-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0024_alter_businessreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
