# Generated by Django 4.2.7 on 2026-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0026_reportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingcatalogqueue',
            name='parent_asin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parent_asin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='parent_asin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
