# Generated by Django 4.2.7 on 2026-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0027_missingcatalogqueue_parent_asin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreport',
            name='report_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
