# Generated by Django 4.2.7 on 2026-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0028_businessreport_report_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccount',
            name='amazon_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
