# Generated by Django 4.2.7 on 2026-05-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0029_amazonaccount_amazon_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonEstimatedFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_sku', models.CharField(db_index=True, max_length=255)),
                ('asin', models.CharField(blank=True, max_length=50, null=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_item_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fba_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fba_pick_pack_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fba_weight_handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_response', models.JSONField(default=dict)),
                ('estimated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_fees', to='amazon_auth.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['seller_sku'], name='amazon_auth_seller__c0d971_idx'), models.Index(fields=['asin'], name='amazon_auth_asin_462f81_idx')],
            },
        ),
    ]
