# Generated by Django 4.2.7 on 2026-05-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0030_amazonestimatedfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonestimatedfee',
            name='amazon_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_fees', to='amazon_auth.amazonaccount'),
        ),
    ]
