# Generated by Django 4.2.7 on 2026-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0031_amazonestimatedfee_amazon_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonestimatedfee',
            name='fulfillment_channel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
