# Generated by Django 4.2.7 on 2026-05-18 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0032_amazonestimatedfee_fulfillment_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('marketplace_id', models.CharField(default='A21TJRUUN4KGV', max_length=100)),
                ('listing_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('landed_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=20)),
                ('fulfillment_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('item_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asin', 'sku')},
            },
        ),
    ]
