# Generated by Django 4.2.7 on 2026-05-19 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0033_productpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCatalogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=50)),
                ('parent_asin', models.CharField(blank=True, max_length=50, null=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_points', models.JSONField(blank=True, default=list)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('item_weight_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('package_weight', models.FloatField(blank=True, null=True)),
                ('package_weight_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('item_dimensions', models.JSONField(blank=True, default=dict)),
                ('package_dimensions', models.JSONField(blank=True, default=dict)),
                ('number_of_items', models.IntegerField(blank=True, null=True)),
                ('batteries_required', models.BooleanField(blank=True, null=True)),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('special_features', models.JSONField(blank=True, default=list)),
                ('recommended_uses', models.TextField(blank=True, null=True)),
                ('sales_rank', models.IntegerField(blank=True, null=True)),
                ('sales_rank_category', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_attributes', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asin', 'marketplace_id')},
            },
        ),
    ]
