# Generated by Django 4.2.7 on 2026-05-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0034_amazoncatalogdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazoncatalogdetails',
            name='raw_attributes',
        ),
    ]
