# Generated by Django 4.2.7 on 2026-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0035_remove_amazoncatalogdetails_raw_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoncatalogdetails',
            name='display_group_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazoncatalogdetails',
            name='display_group_rank_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
