# Generated by Django 4.2.7 on 2026-05-19 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0036_amazoncatalogdetails_display_group_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('asin', models.CharField(blank=True, max_length=50, null=True)),
                ('marketplace_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.JSONField(blank=True, default=list)),
                ('fnsku', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('offers', models.JSONField(blank=True, default=list)),
                ('fulfillment_availability', models.JSONField(blank=True, default=list)),
                ('relationships', models.JSONField(blank=True, default=list)),
                ('product_types', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='amazon_auth.amazonaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('amazon_account', 'sku', 'marketplace_id')},
            },
        ),
    ]
