# Generated by Django 4.2.7 on 2026-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0037_amazonlistingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlistingitem',
            name='gst_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='amazonlistingitem',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonlistingitem',
            name='shiping_estimate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='amazonlistingitem',
            name='standard_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='amazonlistingitem',
            name='step_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonlistingitem',
            name='tcs',
            field=models.FloatField(default=0),
        ),
    ]
