# Generated by Django 4.2.7 on 2026-06-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0038_amazonlistingitem_gst_rate_amazonlistingitem_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='amazon_auth.amazonaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonTransactionRelatedIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_name', models.CharField(max_length=255)),
                ('identifier_value', models.CharField(max_length=255)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_identifiers', to='amazon_auth.amazontransaction')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonTransactionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(blank=True, max_length=255, null=True)),
                ('asin', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_shipped', models.IntegerField(blank=True, null=True)),
                ('fulfillment_network', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_context', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='amazon_auth.amazontransaction')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonTransactionBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='amazon_auth.amazontransactionbreakdown')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='amazon_auth.amazontransaction')),
            ],
        ),
    ]
