# Generated by Django 4.2.7 on 2026-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0039_amazontransaction_amazontransactionrelatedidentifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='deferral_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='order_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazontransactioncontext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
