# Generated by Django 4.2.7 on 2026-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0040_amazontransactioncontext_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='new_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
