# Generated by Django 4.2.7 on 2026-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0041_order_new_item_price_order_new_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_item_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='new_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
