# Generated by Django 4.2.7 on 2026-08-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0043_exportedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoncatalogdetails',
            name='item_type_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
