# Generated by Django 4.2.7 on 2026-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0043_exportedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccount',
            name='initial_sync_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonaccount',
            name='initial_sync_required',
            field=models.BooleanField(default=False),
        ),
    ]
