# Generated by Django 4.2.7 on 2026-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0044_amazonaccount_initial_sync_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccount',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amazoncatalogdetails',
            name='item_type_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
