# Generated by Django 4.2.7 on 2026-08-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0044_alter_amazoncatalogdetails_item_type_name'),
        ('amazon_auth', '0045_amazonaccount_store_name_and_more'),
    ]

    operations = [
    ]
