# Generated by Django 4.2.27 on 2026-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0046_merge_20260821_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlistingitem',
            name='tds',
            field=models.FloatField(default=0),
        ),
    ]
