# Generated by Django 4.2.27 on 2026-08-31 07:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0047_amazonlistingitem_tds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCalculationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcs', models.BooleanField(default=True)),
                ('tds', models.BooleanField(default=True)),
                ('gst_treatment', models.CharField(default='adjusted', max_length=20)),
                ('input_gst_itc', models.BooleanField(default=True)),
                ('output_gst', models.BooleanField(default=True)),
                ('claim', models.BooleanField(default=True)),
                ('product_cost', models.BooleanField(default=True)),
                ('ad_spend', models.BooleanField(default=True)),
                ('other_expense', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_calculation_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_auth_profitcalculationsetting',
            },
        ),
    ]
