# Generated by Django 4.2.27 on 2026-08-31 10:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0048_profitcalculationsetting_otherexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitcalculationsetting',
            name='preview_input_gst_rate',
            field=models.FloatField(default=0.18),
        ),
        migrations.AddField(
            model_name='profitcalculationsetting',
            name='preview_other_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='profitcalculationsetting',
            name='preview_output_gst_rate',
            field=models.FloatField(default=0.05),
        ),
    ]
