# Generated by Django 4.2.7 on 2026-09-18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0050_marketplaceestimatedfeerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitcalculationsetting',
            name='preview_net_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='profitcalculationsetting',
            name='preview_product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
