# Generated by Django 4.2.7 on 2026-09-18 16:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_otherexpense_if_not_exists(apps, schema_editor):
    table_name = 'amazon_auth_otherexpense'
    with schema_editor.connection.cursor() as cursor:
        table_names = schema_editor.connection.introspection.table_names(cursor)
        if table_name not in table_names:
            OtherExpense = apps.get_model('amazon_auth', 'OtherExpense')
            schema_editor.create_model(OtherExpense)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_auth', '0051_profitcalculationsetting_preview_net_sales_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OtherExpense',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('expense_name', models.CharField(max_length=255)),
                        ('marketplace', models.CharField(default='Amazon', max_length=50)),
                        ('cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('cost_type', models.CharField(choices=[('per_sku', 'Per SKU'), ('per_order', 'Per Order')], default='per_sku', max_length=20)),
                        ('split_lump_sum_by', models.CharField(choices=[('equally', 'Equally across SKUs'), ('net_sales', 'By net sales'), ('units_sold', 'By units sold')], default='equally', max_length=50)),
                        ('repeat_monthly', models.BooleanField(default=False)),
                        ('status', models.CharField(choices=[('applied', 'Applied'), ('recalculating', 'Recalculating'), ('draft', 'Draft')], default='applied', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'amazon_auth_otherexpense',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_otherexpense_if_not_exists, reverse_code=migrations.RunPython.noop),
            ]
        ),
    ]
