# Generated by Django 4.2.7 on 2026-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0052_otherexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
