# Generated by Django 5.1.4 on 2026-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_usersubscription_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
