# Generated by Django 4.2.7 on 2026-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_usersubscription_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
