# Generated by Django 4.2.27 on 2026-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_usersubscription_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='expired_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_1day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_3day_sent',
            field=models.BooleanField(default=False),
        ),
    ]
