# Generated by Django 4.2.27 on 2026-09-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_subscriptionplan_max_channel_connection'),
        ('subscription', '0006_usersubscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='next_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_user_subscriptions', to='user_auth.subscriptionplan'),
        ),
    ]
