# Generated by Django 4.2.7 on 2026-05-13 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(unique=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], default='EU', max_length=10)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('account_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=50, null=True)),
                ('targeting_type', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_budget', models.FloatField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('acos', models.FloatField(default=0)),
                ('roas', models.FloatField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
            options={
                'unique_together': {('campaign', 'report_date')},
            },
        ),
    ]
