# Generated by Django 4.2.7 on 2026-05-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_auth', '0032_amazonestimatedfee_fulfillment_channel'),
        ('amazon_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadsaccount',
            name='amazon_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon_auth.amazonaccount'),
        ),
    ]
