# Generated by Django 4.2.7 on 2026-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0002_amazonadsaccount_amazon_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadsaccount',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
