# Generated by Django 4.2.7 on 2026-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0003_amazonadsaccount_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscampaign',
            name='bidding_strategy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adscampaign',
            name='budget_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adscampaign',
            name='marketplace_budget_allocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adscampaign',
            name='off_amazon_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adscampaign',
            name='placement_bidding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adscampaign',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='cpc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='ctr',
            field=models.FloatField(default=0),
        ),
    ]
