# Generated by Django 4.2.7 on 2026-05-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0004_adscampaign_bidding_strategy_adscampaign_budget_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('default_bid', models.FloatField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdsTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.BigIntegerField(unique=True)),
                ('expression_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.JSONField(default=list)),
                ('bid', models.FloatField(default=0)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adsadgroup')),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdsReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('download_url', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AdsProductAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField(unique=True)),
                ('asin', models.CharField(max_length=20)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adsadgroup')),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.BigIntegerField(unique=True)),
                ('keyword_text', models.TextField()),
                ('match_type', models.CharField(choices=[('BROAD', 'BROAD'), ('PHRASE', 'PHRASE'), ('EXACT', 'EXACT')], max_length=20)),
                ('bid', models.FloatField(default=0)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adsadgroup')),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
        ),
    ]
