# Generated by Django 4.2.7 on 2026-05-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0005_adsadgroup_adstarget_adsreportlog_adsproductad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adstarget')),
            ],
        ),
        migrations.CreateModel(
            name='SearchTermMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField()),
                ('report_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('acos', models.FloatField(default=0)),
                ('roas', models.FloatField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adscampaign')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('product_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adsproductad')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('acos', models.FloatField(default=0)),
                ('roas', models.FloatField(default=0)),
                ('raw_data', models.JSONField(default=dict)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.adskeyword')),
            ],
            options={
                'unique_together': {('keyword', 'report_date')},
            },
        ),
    ]
