# Generated by Django 4.2.7 on 2026-05-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0006_targetmetric_searchtermmetric_productadmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBudgetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('associated_campaigns_count', models.IntegerField(default=0)),
                ('created_at_amazon', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at_amazon', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
        ),
    ]
