# Generated by Django 4.2.7 on 2026-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0007_adsbudgetrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbudgetrule',
            name='budget_rule_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
