# Generated by Django 4.2.7 on 2026-05-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0008_adsbudgetrule_budget_rule_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsbudgetrule',
            old_name='state',
            new_name='rule_state',
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='budget_rule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='created_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='last_updated_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='rule_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='adsbudgetrule',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adsbudgetrule',
            name='rule_type',
            field=models.CharField(choices=[('sp', 'Sponsored Products'), ('sd', 'Sponsored Display'), ('sb', 'Sponsored Brands')], default='sp', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='adsbudgetrule',
            unique_together={('amazon_account', 'budget_rule_id', 'rule_type')},
        ),
        migrations.RemoveField(
            model_name='adsbudgetrule',
            name='associated_campaigns_count',
        ),
        migrations.RemoveField(
            model_name='adsbudgetrule',
            name='budget_rule_details',
        ),
        migrations.RemoveField(
            model_name='adsbudgetrule',
            name='created_at_amazon',
        ),
        migrations.RemoveField(
            model_name='adsbudgetrule',
            name='last_updated_at_amazon',
        ),
        migrations.RemoveField(
            model_name='adsbudgetrule',
            name='rule_id',
        ),
    ]
