# Generated by Django 4.2.7 on 2026-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0009_rename_state_adsbudgetrule_rule_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbudgetrule',
            name='rule_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
