# Generated by Django 4.2.7 on 2026-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0010_adsbudgetrule_rule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adskeyword',
            name='keyword_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='adstarget',
            name='target_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
