# Generated by Django 4.2.7 on 2026-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0011_alter_adskeyword_keyword_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbudgetrule',
            name='campaign_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='error_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adsbudgetrule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
