# Generated by Django 4.2.7 on 2026-06-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0013_adscampaignnegativetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsNegativeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_keyword_id', models.BigIntegerField(unique=True)),
                ('keyword_text', models.TextField()),
                ('match_type', models.CharField(blank=True, choices=[('NEGATIVE_EXACT', 'NEGATIVE_EXACT'), ('NEGATIVE_PHRASE', 'NEGATIVE_PHRASE'), ('NEGATIVE_BROAD', 'NEGATIVE_BROAD')], max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_status', models.CharField(blank=True, max_length=100, null=True)),
                ('native_language_keyword', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negative_keywords', to='amazon_ads.adsadgroup')),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_keywords', to='amazon_ads.adscampaign')),
            ],
            options={
                'unique_together': {('amazon_account', 'negative_keyword_id')},
            },
        ),
    ]
