# Generated by Django 4.2.7 on 2026-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0014_adsnegativekeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsnegativekeyword',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsnegativekeyword',
            name='last_update_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
