# Generated by Django 4.2.7 on 2026-06-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0015_adsnegativekeyword_creation_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsOptimizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('optimization_rule_id', models.CharField(max_length=255, unique=True)),
                ('rule_name', models.CharField(blank=True, max_length=500, null=True)),
                ('rule_category', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('recurrence', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
        ),
    ]
