# Generated by Django 4.2.7 on 2026-06-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0016_adsoptimizationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('in_budget', models.BooleanField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('budget_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
        ),
    ]
