# Generated by Django 4.2.7 on 2026-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0017_adsportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
