# Generated by Django 4.2.7 on 2026-06-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0018_adscampaign_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsNegativeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_target_id', models.BigIntegerField(unique=True)),
                ('expression_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.JSONField(blank=True, default=list)),
                ('resolved_expression', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_status', models.CharField(blank=True, max_length=100, null=True)),
                ('bid', models.FloatField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negative_targets', to='amazon_ads.adsadgroup')),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_targets', to='amazon_ads.adscampaign')),
            ],
            options={
                'unique_together': {('amazon_account', 'negative_target_id')},
            },
        ),
        migrations.AlterField(
            model_name='adsportfolio',
            name='portfolio_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='adsportfolio',
            unique_together={('amazon_account', 'portfolio_id')},
        ),
        migrations.DeleteModel(
            name='AdsCampaignNegativeTarget',
        ),
    ]
