# Generated by Django 4.2.7 on 2026-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0019_adsnegativetarget_alter_adsportfolio_portfolio_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsnegativetarget',
            name='bid',
        ),
        migrations.AddField(
            model_name='adsnegativetarget',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsnegativetarget',
            name='last_update_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
