# Generated by Django 4.2.7 on 2026-08-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0020_remove_adsnegativetarget_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadsaccount',
            name='initial_sync_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonadsaccount',
            name='initial_sync_required',
            field=models.BooleanField(default=False),
        ),
    ]
