# Generated by Django 4.2.7 on 2026-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0021_amazonadsaccount_initial_sync_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadsaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonadsaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='amazonadsaccount',
            name='amazon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonadsaccount',
            name='marketplace_string_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
