# Generated by Django 4.2.7 on 2026-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0022_amazonadsaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonadsaccount',
            name='profile_id',
            field=models.BigIntegerField(),
        ),
    ]
