# Generated by Django 4.2.7 on 2026-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0023_alter_amazonadsaccount_profile_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amazonadsaccount',
            constraint=models.UniqueConstraint(fields=('user', 'profile_id'), name='unique_ads_profile_per_user'),
        ),
    ]
