# Generated by Django 4.2.7 on 2026-08-17 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlinkitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blinkit_user_id', models.CharField(max_length=255)),
                ('blinkit_password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blinkit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlinkitImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('ORDER_FINANCIAL', 'Order Financial'), ('LISTING', 'Listing')], max_length=50)),
                ('payout_period_start', models.DateField(blank=True, null=True)),
                ('payout_period_end', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='blinkit.blinkitaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BlinkitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_kind', models.CharField(choices=[('FORWARD', 'Forward'), ('RETURN', 'Return'), ('CANCELLED', 'Cancelled')], default='FORWARD', max_length=20)),
                ('order_type', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('forward_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('return_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('return_order_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_gst_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_state', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='blinkit.blinkitaccount')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='BlinkitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upc_ean', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('business_category', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_commission_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('platform_commission_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fulfillment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inwarding_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, max_length=100, null=True)),
                ('expansion_level', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blinkit.blinkitaccount')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='blinkit.blinkitimportbatch')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='BlinkitPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_period_start', models.DateField()),
                ('payout_period_end', models.DateField()),
                ('bank_utr', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('settlement_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='blinkit.blinkitaccount')),
            ],
            options={
                'ordering': ['-payout_period_end'],
            },
        ),
        migrations.CreateModel(
            name='BlinkitOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variant_description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('igst_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cgst_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('sgst_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cess_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gross_bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('commission_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_194o_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_194q_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_additions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_level_payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unsettled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blinkit.blinkitorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='blinkit.blinkitproduct')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='blinkit.blinkitimportbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blinkitorder',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='blinkit.blinkitpayout'),
        ),
        migrations.AddField(
            model_name='blinkitorder',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='blinkit.blinkitimportbatch'),
        ),
        migrations.AddIndex(
            model_name='blinkitproduct',
            index=models.Index(fields=['account', 'item_id'], name='blinkit_bli_account_a9e326_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitproduct',
            index=models.Index(fields=['account', 'product_id'], name='blinkit_bli_account_e7539b_idx'),
        ),
        migrations.AddConstraint(
            model_name='blinkitproduct',
            constraint=models.UniqueConstraint(fields=('account', 'item_id'), name='unique_blinkit_product_item'),
        ),
        migrations.AddConstraint(
            model_name='blinkitpayout',
            constraint=models.UniqueConstraint(fields=('account', 'payout_period_start', 'payout_period_end'), name='unique_blinkit_payout_period'),
        ),
        migrations.AddIndex(
            model_name='blinkitorderitem',
            index=models.Index(fields=['item_id'], name='blinkit_bli_item_id_35bf0a_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitorderitem',
            index=models.Index(fields=['order', 'item_id'], name='blinkit_bli_order_i_7efbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitorder',
            index=models.Index(fields=['account', 'order_id'], name='blinkit_bli_account_8d5384_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitorder',
            index=models.Index(fields=['account', 'invoice_id'], name='blinkit_bli_account_01e6be_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitorder',
            index=models.Index(fields=['account', 'order_date'], name='blinkit_bli_account_248d91_idx'),
        ),
        migrations.AddConstraint(
            model_name='blinkitorder',
            constraint=models.UniqueConstraint(fields=('account', 'order_id', 'order_kind'), name='unique_blinkit_order'),
        ),
    ]
