# Generated by Django 4.2.7 on 2026-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blinkitorder',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='blinkitorderitem',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='blinkitproduct',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
