# Generated by Django 4.2.7 on 2026-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkit', '0002_blinkitorder_raw_data_blinkitorderitem_raw_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinkitorder',
            name='raw_data',
        ),
        migrations.AlterField(
            model_name='blinkitorder',
            name='order_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blinkitorder',
            name='order_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blinkitorder',
            name='order_kind',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('RETURN', 'Return'), ('CANCELLED', 'Cancelled')], db_index=True, default='FORWARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='blinkitorder',
            name='order_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blinkitorderitem',
            name='item_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='blinkitorder',
            index=models.Index(fields=['account', 'order_kind'], name='blinkit_bli_account_33fc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='blinkitorderitem',
            index=models.Index(fields=['product'], name='blinkit_bli_product_80a33b_idx'),
        ),
        migrations.AddConstraint(
            model_name='blinkitorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item_id'), name='unique_blinkit_order_item'),
        ),
    ]
