# Generated by Django 4.2.7 on 2026-08-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blinkit', '0003_remove_blinkitorder_raw_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlinkitStorageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_type', models.CharField(max_length=50)),
                ('per_day_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_inventory_unit_days', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('regime', models.CharField(blank=True, max_length=100, null=True)),
                ('ageing_slab', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_charges', to='blinkit.blinkitaccount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_charges', to='blinkit.blinkitproduct')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_charges', to='blinkit.blinkitimportbatch')),
            ],
        ),
    ]
