# Generated by Django 4.2.7 on 2026-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkit', '0004_blinkitstoragecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinkitimportbatch',
            name='report_type',
            field=models.CharField(choices=[('ORDER_FINANCIAL', 'Order Financial'), ('LISTING', 'Listing'), ('STORAGE', 'Storage')], max_length=50),
        ),
    ]
